### ISSUE TITLE
Replace Metadata with Persistent Storage

### ISSUE THREAD

**Issue by gcarvellas** [BuildTheEarthNewJersey/BTEStats#6]
When the server restarts, block metadata is not saved. Persistent storage will fix this issue.

**Comment by gcarvellas** [comment]
Error appears during runtime: ` org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[server.jar:git-Bukkit-f4830a1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Bukkit-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Bukkit-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Bukkit-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:920) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:55) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(SourceFile:11) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Bukkit-f4830a1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [server.jar:git-Bukkit-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [server.jar:git-Bukkit-f4830a1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/persistence/PersistentDataContainer
	at btestats.btestats.Events.AddBlockPlace.onBlockPlace(AddBlockPlace.java:28) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[server.jar:git-Bukkit-f4830a1]
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.persistence.PersistentDataContainer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[server.jar:git-Bukkit-f4830a1]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[server.jar:git-Bukkit-f4830a1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at btestats.btestats.Events.AddBlockPlace.onBlockPlace(AddBlockPlace.java:28) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[server.jar:git-Bukkit-f4830a1]
	... 18 more`

**Comment by gcarvellas** [comment]
Our server uses 1.12.2 and PersistentDataStorage is not in that version of spigot. We need to look into using DB instead to keep track of block history.

**Comment by gcarvellas** [comment]
@mkowalczyk570 This might be worth looking into. Currently the coordinates are converted into a string of doubles in the DB, but we may be able to convert the coordinates into one number https://www.spigotmc.org/threads/tracking-blocks-that-were-placed-by-players.500216/
